services:
  - type: web
    name: cut-autoeditor
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
